web:
  build: .
  command: python /code/hasjob/rundockerserver.py
  volumes:
   - .:/code/hasjob
  environment:
    SERVER_NAME: hasjob.docker.dev
    LASTUSER_SERVER: https://auth.hasgeek.com
    LASTUSER_CLIENT_ID: client-key-here
    LASTUSER_CLIENT_SECRET: client-secret-here
  links:
   - pg
   - redis
   - postfix
  ports:
   - "5000:5000"
   - "5432:5432"
   - "6379:6379"
   - "25:25"
pg:
  image: postgres
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
redis:
  image: redis
postfix:
  image: hasgeek/postfix
  environment:
    SMTP_SERVER: smtp.bar.com
    SMTP_USERNAME: foo@bar.com
    SMTP_PASSWORD: XXXXXXXX
    SMTP_HOSTNAME: helpdesk.mycompany.com